#!/usr/bin/env node
/**
 * Merges the split authoring files into the single data modules the app loads.
 *   data/units/uNN.js         -> data/vocab.js        (export `vocab`)
 *   data/src/grammar-*.js     -> data/grammar.js      (export `grammar`)
 *   data/src/drills-*.js      -> data/drills.js       (export `drills`)
 *   data/src/readings-*.js    -> data/readings.js     (export `readings`)
 * Also writes data/index.js, the manifest the app imports.
 *
 * Run from the repo root:  node tools/build.js
 */
import { readdir, writeFile, mkdir } from "node:fs/promises";
import { existsSync } from "node:fs";
import { pathToFileURL } from "node:url";
import path from "node:path";

const ROOT = process.cwd();
const SRC = path.join(ROOT, "data/src");
const stamp = Date.now();

async function importAbs(abs) {
  return import(pathToFileURL(abs).href + `?t=${stamp}`);
}

async function listSrc(prefix) {
  if (!existsSync(SRC)) return [];
  const files = await readdir(SRC);
  return files.filter((f) => f.startsWith(prefix) && f.endsWith(".js")).sort();
}

function serialize(value, indent = 0) {
  const pad = "  ".repeat(indent);
  const padIn = "  ".repeat(indent + 1);
  if (value === null) return "null";
  if (value === undefined) return "undefined";
  if (typeof value === "string") return JSON.stringify(value);
  if (typeof value === "number" || typeof value === "boolean") return String(value);
  if (Array.isArray(value)) {
    if (!value.length) return "[]";
    const flat = value.every((v) => typeof v !== "object" || v === null);
    if (flat) {
      const oneLine = "[" + value.map((v) => serialize(v)).join(", ") + "]";
      if (oneLine.length <= 100) return oneLine;
    }
    return "[\n" + value.map((v) => padIn + serialize(v, indent + 1)).join(",\n") + "\n" + pad + "]";
  }
  const entries = Object.entries(value).filter(([, v]) => v !== undefined);
  if (!entries.length) return "{}";
  const oneLine =
    "{ " + entries.map(([k, v]) => `${keyOf(k)}: ${serialize(v)}`).join(", ") + " }";
  if (oneLine.length <= 100 && !oneLine.includes("\n")) return oneLine;
  return (
    "{\n" +
    entries.map(([k, v]) => `${padIn}${keyOf(k)}: ${serialize(v, indent + 1)}`).join(",\n") +
    "\n" +
    pad +
    "}"
  );
}

const keyOf = (k) => (/^[A-Za-z_$][A-Za-z0-9_$]*$/.test(k) ? k : JSON.stringify(k));

async function emit(file, name, arr, note) {
  const header =
    `// GENERATED by tools/build.js — do not edit by hand.\n` +
    `// ${note}\n` +
    `// ${arr.length} entries.\n\n`;
  const body = `export const ${name} = ${serialize(arr, 0)};\n\nexport default ${name};\n`;
  await writeFile(path.join(ROOT, file), header + body, "utf8");
  console.log(`  ${file.padEnd(24)} ${String(arr.length).padStart(5)} entries`);
}

async function mergeSrc(prefix, exportName, outFile, key) {
  const files = await listSrc(prefix);
  const out = [];
  const seen = new Map();
  for (const f of files) {
    const mod = await importAbs(path.join(SRC, f));
    const arr = mod[exportName] || mod.default;
    if (!Array.isArray(arr)) {
      console.warn(`  ! data/src/${f} does not export an array named ${exportName}`);
      continue;
    }
    for (const item of arr) {
      const id = item && item[key];
      if (id && seen.has(id)) {
        console.warn(`  ! duplicate ${key}=${JSON.stringify(id)} in data/src/${f} (kept the first from ${seen.get(id)})`);
        continue;
      }
      if (id) seen.set(id, f);
      out.push(item);
    }
  }
  await emit(outFile, exportName, out, `merged from data/src/${prefix}*.js`);
  return out.length;
}

async function main() {
  console.log("Building data modules…");
  await mkdir(SRC, { recursive: true });

  /* ---- units -> vocab.js + units manifest ---- */
  const unitsDir = path.join(ROOT, "data/units");
  let unitFiles = [];
  if (existsSync(unitsDir)) {
    unitFiles = (await readdir(unitsDir)).filter((f) => /^u\d\d\.js$/.test(f)).sort();
  }
  const vocab = [];
  const seenWord = new Map();
  for (const f of unitFiles) {
    const mod = await importAbs(path.join(unitsDir, f));
    const list = mod.vocab;
    if (!Array.isArray(list)) {
      console.warn(`  ! data/units/${f} exports no vocab array`);
      continue;
    }
    for (const v of list) {
      if (!v || !v.w) continue;
      if (seenWord.has(v.w)) {
        // Keep the earliest introduction; later units may legitimately re-list a word.
        continue;
      }
      seenWord.set(v.w, f);
      vocab.push(v);
    }
  }
  vocab.sort((a, b) => (a.unit - b.unit) || a.w.localeCompare(b.w, "is"));
  await emit("data/vocab.js", "vocab", vocab, "merged from the vocab export of every data/units/uNN.js");

  /* ---- src merges ---- */
  await mergeSrc("grammar-", "grammar", "data/grammar.js", "id");
  await mergeSrc("drills-", "drills", "data/drills.js", "id");
  await mergeSrc("readings-", "readings", "data/readings.js", "id");

  /* ---- lightweight unit manifest (full unit bodies are imported lazily) ---- */
  const manifest = [];
  for (const f of unitFiles) {
    const mod = await importAbs(path.join(unitsDir, f));
    const u = mod.unit || mod.default;
    if (!u) continue;
    manifest.push({
      id: u.id,
      slug: u.slug,
      title: u.title,
      en: u.en,
      cefr: u.cefr,
      icon: u.icon,
      blurb: u.blurb,
      canDo: u.canDo,
      words: Array.isArray(mod.vocab) ? mod.vocab.length : 0,
      lessons: (u.lessons || []).map((l) => ({
        n: l.n,
        id: l.id,
        kind: l.kind,
        title: l.title,
        en: l.en,
        goal: l.goal,
        minutes: l.minutes,
        icon: l.icon,
        items: Array.isArray(l.items) ? l.items.length : 0
      }))
    });
  }
  manifest.sort((a, b) => a.id - b.id);
  await emit("data/manifest.js", "manifest", manifest, "unit + lesson metadata; unit bodies load on demand");

  /* ---- asset list for the service worker ---- */
  const slugs = unitFiles.map((f) => f.replace(/\.js$/, ""));
  const unitPaths = slugs.map((s) => `./data/units/${s}.js`);
  await writeFile(
    path.join(ROOT, "data/unit-files.js"),
    `// GENERATED by tools/build.js — do not edit by hand.\n` +
      `export const unitFiles = ${JSON.stringify(unitPaths, null, 2)};\n\nexport default unitFiles;\n`,
    "utf8"
  );
  console.log(`  data/unit-files.js       ${String(slugs.length).padStart(5)} units`);

  console.log("Done.");
}

main().catch((e) => {
  console.error("build failed:", e);
  process.exit(1);
});
